---
- name: get docker key
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -"
  become: true

- name: check docker key fingerprint
  command: "apt-key fingerprint 0EBFCD88"
  become: true

- name: add repo matching distro
  shell: "add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\""

- name: install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: true
