---
- name: get docker key
  shell: "curl -fsSL https://yum.dockerproject.org/gpg | apt-key add -"

- name: check docker key fingerprint
  command: "apt-key fingerprint 58118E89F3A912897C070ADBF76221572C52609D"

- name: add repo matching distro
  shell: "add-apt-repository \"deb https://apt.dockerproject.org/repo/ ubuntu-$(lsb_release -cs) main\""

- name: install docker-engine
  apt:
    name: docker-engine
    state: present
