---
- name: get git-secret key
  shell: "curl -fsSL https://api.bintray.com/users/sobolevn/keys/gpg/public.key | apt-key add -"

- name: add repo
  shell: "add-apt-repository \"deb https://dl.bintray.com/sobolevn/deb git-secret main\""

- name: install git-secret
  apt:
    name: git-secret
    state: present
