---
- name: Install prerequisites for Google Chrome repository
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: Create directory for Google Chrome GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Google Chrome GPG key
  get_url:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/keyrings/google-chrome.asc
    mode: "0644"
    force: true

- name: Add Google Chrome repository
  deb822_repository:
    name: google-chrome
    types: [deb]
    uris: "http://dl.google.com/linux/chrome/deb/"
    suites: [stable]
    components: [main]
    architectures: [amd64]
    signed_by: /etc/apt/keyrings/google-chrome.asc
    state: present

- name: Install Google Chrome Beta
  apt:
    name: google-chrome-beta
    state: latest
    update_cache: true
