##
# Ansible playbook for setting up a LAMP development server on Ubuntu 14.04.
#

---

- hosts: local
  user: naugtur
  become: true #new syntax for sudo

  vars_files:
    - group_vars/all.yml

  roles:
    - common       # List of essential packages
    - nodejs
    - atom
    - flux
    - skype
