---

- name: Linux | Update cache
  apt: update_cache=yes cache_valid_time=3600

- name: Linux | Upgrade
  apt: upgrade=dist

- name: Package | Add apt https
  apt: pkg={{ item }} state=installed
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Package | Install sys/console tools
  apt: pkg={{ item }} state=installed
  with_items:
    - aptitude
    - bash-completion
    - openssh-server
    - vim
    - git
    - git-core
    - curl
    - wget
    - htop
    - atop
    - iotop
    - iftop
    - unzip
    - tar
    - gzip
    - bzip2
    - byobu
    - baobab
    - build-essential
    - nmap

- name: Package | Install programs
  apt: pkg={{ item }} state=installed
  with_items:
    - firefox
    - links2
    - vlc
    - gimp
    - easytag
    - audacity
    - redis-server
    - mongodb
    - chromium-browser
    - inkscape
    - calibre

# - name: Package | Remove unwanted
#   apt: pkg={{ item }} state=absent
#   with_items:

# doesn't seem to work with current ansible
# - name: Package | autoremove
#   apt:
#     autoremove: yes
