---

- name: Linux | Update cache
  apt: update_cache=yes cache_valid_time=3600

- name: Linux | Upgrade
  apt: upgrade=dist

- name: Package | Add apt https
  apt: 
    pkg:
      - apt-transport-https
      - ca-certificates

- name: Package | Install sys/console tools
  apt: 
    pkg:
    - aptitude
    - bash-completion
    - openssh-server
    - vim
    - git
    - git-core
    - curl
    - wget
    - htop
    - atop
    - iotop
    - iftop
    - unzip
    - tar
    - gzip
    - bzip2
    - byobu
    - baobab
    - build-essential
    - nmap
  

- name: Package | Install programs
  apt: 
    pkg:
      - testdisk #awesome recovery tool 
      - links2
      - vlc
      - gimp
      - easytag
      - audacity
      - chromium-browser
      - inkscape
      - calibre
      - nodejs


