---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages to latest version
  apt:
    upgrade: dist

- name: Install apt transport packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Install system and console tools
  apt:
    name:
      - aptitude
      - bash-completion
      - openssh-server
      - vim
      - git
      - git-core
      - curl
      - wget
      - htop
      - atop
      - iotop
      - iftop
      - unzip
      - tar
      - gzip
      - bzip2
      - byobu
      - baobab
      - build-essential
      - nmap
      - xdotool
    state: present

- name: Install desktop applications
  apt:
    name:
      - testdisk # awesome recovery tool
      - links2
      - vlc
      - gimp
      - easytag
      - audacity
      - chromium-browser
      - inkscape
      - calibre
      - nodejs
      - recordmydesktop
      - kdeconnect
      - gufw
    state: present
