---
- name: Copy bin scripts to user home directory
  become: false
  copy:
    src: "{{ playbook_dir }}/scripts/bin"
    dest: "~/"
    mode: preserve
    backup: true
  tags:
    - binscripts

- name: Ensure bin directory is executable
  become: false
  file:
    path: "~/bin"
    mode: "0755"
    recurse: true
  tags:
    - binscripts

- name: Add bin directory to PATH in .bashrc
  become: false
  lineinfile:
    path: "~/.bashrc"
    line: 'export PATH="$HOME/bin:$PATH"'
    regexp: '^export PATH="\$HOME/bin:\$PATH"'
    state: present
    backup: true
  tags:
    - binscripts
