---
- import_tasks: theme.yml
- import_tasks: binscripts.yml
- import_tasks: shortcuts.yml
- import_tasks: tweaks.yml

- name: Check SSD trim cron
  stat:
    path: /etc/cron.weekly/fstrim
  register: cronweekly
# - name: Trim SSD daily
#   command:
#     cmd: mv /etc/cron.weekly/fstrim /etc/cron.daily/fstrim
#     creates: /etc/cron.daily/fstrim
#   when: cronweekly.stat.exists
