---
- name: Install xfconf
  apt:
    name: xfconf
    state: present

# Note: These keyboard shortcuts may not work reliably due to XFCE limitations

- name: Add dropdown terminal shortcut
  become: true
  become_user: "{{ user }}"
  shell: "xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/commands/custom/<Primary>grave' --type string --set 'xfce4-terminal --drop-down'"

- name: Configure window tiling shortcuts
  become: true
  become_user: "{{ user }}"
  shell: |
    # Right tile with super + right arrow
    xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/xfwm4/custom/<Super>Right' --type string --set 'tile_right_key'
    # Left tile with super + left arrow
    xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/xfwm4/custom/<Super>Left' --type string --set 'tile_left_key'
    # Maximize horizontal
    xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/xfwm4/custom/<Super>a' --type string --set 'maximize_horiz_key'
    # Maximize vertical
    xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/xfwm4/custom/<Super>q' --type string --set 'maximize_vert_key'
