---
- name: Add canonical partner list deb
  apt_repository:
    repo: 'deb http://archive.canonical.com/ {{ ansible_distribution_release }} partner'
    state: present
    mode: '0644'

- name: Install skype
  apt:
    pkg: skype
    state: latest
